apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80    # exposed port in the cluster
      targetPort: 8000     # container port
  type: ClusterIP

